### ISSUE TITLE
Outdated webpack plugin usage?

### ISSUE THREAD

**Issue by sp00x** [egoist/vue-monaco#12] opened 2018-09-27 13:29 UTC
The webpack plugin usage seems outdated - I guess you're supposed to do it something like this now?

```javascript
const MonacoEditorPlugin = require('monaco-editor-webpack-plugin')

module.exports = {
  configureWebpack: {
    plugins: [
      new MonacoEditorPlugin()
    ]
  }
}
```

Which didn't go well with `npm run serve`

```
ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'monaco-editor\esm\vs\language\typescript\lib\typescriptServices'
Error: Cannot find module 'monaco-editor\esm\vs\language\typescript\lib\typescriptServices'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at resolveMonacoPath (c....\node_modules\monaco-editor-webpack-plugin\index.js:35:18)
    at Object.<anonymous> (c:.....\node_modules\monaco-editor-webpack-plugin\index.js:7:4)
``` 

So, I tried `npm i -S monaco-editor`, but that gave new interesting errors.. because it's probably a too new version.

```
Error: Cannot find module 'monaco-editor\esm\vs\editor\contrib\fontZoom\fontZoom'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at resolveMonacoPath (c<project-path>\node_modules\monaco-editor-webpack-plugin\index.js:21:18)
    at use.options.pre.featurePaths.map (c<project-path>\node_modules\monaco-editor-webpack-plugin\index.js:133:51)
    at Array.map (<anonymous>)
    at createLoaderRules (c<project-path>\node_modules\monaco-editor-webpack-plugin\index.js:133:31)
    at MonacoWebpackPlugin.apply (c<project-path>\node_modules\monaco-editor-webpack-plugin\index.js:71:19)
    at webpack (c<project-path>\node_modules\webpack\lib\webpack.js:37:12)
    at serve (c<project-path>\node_modules\@vue\cli-service\lib\commands\serve.js:112:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Eventually I uninstalled both the monaco-editor and monaco-editor-webpack-plugin packages that were @ latest and did the ones in the package.json of the vue-monaco project, and then it seems to work better..

i.e. `npm i -S monaco-editor@0.13.1 monaco-editor-webpack-plugin@1.4.0`

Maybe some updating is in order here to clarify and correct this?

Which version of monaco-editor and/or the webpack plugin needs to be installed?

**Comment by ramiy** [comment] 2018-11-03 19:02
See https://github.com/rethinkdb/rethinkdb-desktop/issues/44

@DMXL say's that **monaco-editor-webpack-plugin** requires `monaco-editor@0.14.1`, while **vue-monaco** requires `monaco-editor@0.13.1`.

**Comment by DMXL** [comment] 2018-11-07 10:36
@ramiy My references of the plugin version were messed up in that reply (corrected now). Yet you still manage to get what I actually meant somehow. Masterful and patient I'd say.

**Comment by ramiy** [comment] 2018-12-05 23:19
The issue is fixed with newer packages.

I've upgraded to `monaco-editor@0.15.1` and `monaco-editor-webpack-plugin@1.7.0` and all the errors are gone.

**Comment by egoist** [comment] 2019-01-04 19:04
As @ramiy said, it should be resolved by the latest version of `monaco-editor-webpack-plugin@1.7.0`

**Closed by egoist** 2019-01-04 19:04 UTC
